package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TestBuilder2'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TestBuilder2")) {
    expectSteps {
        script {
            scriptContent = "echo build2"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = """
                echo build2
                ping 127.0.0.1 -n 300 > nul
            """.trimIndent()
        }
    }
}
